apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # Name of the ArgoCD application
  name: online-shop-app

  # ArgoCD applications must be created in argocd namespace
  namespace: argocd

spec:
  # ArgoCD project (default is fine for learning)
  project: default

  source:
    # Git repository containing Kubernetes manifests
    repoURL: https://github.com/MrSharma151/argocd-demos.git

    # Git branch or tag to track
    targetRevision: main

    # Path inside repo where manifests are stored
    path: declarative_approach/online_shop

  destination:
    # In-cluster Kubernetes API (BEST PRACTICE)
    # Never hardcode cluster IPs in GitOps
    server: https://kubernetes.default.svc

    # Namespace where application resources will be deployed
    namespace: online-shop

  syncPolicy:
    automated:
      # Automatically delete resources removed from Git
      prune: true

      # Automatically fix manual changes (drift correction)
      selfHeal: true
