apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # Name of the NGINX child application
  name: nginx-child
  namespace: argocd
spec:
  project: devops-project

  source:
    # Git repository containing NGINX manifests
    repoURL: https://github.com/MrSharma151/argocd-demos.git
    targetRevision: main
    # Path of NGINX app deployed earlier via UI approach
    path: ui_approach/nginx

  destination:
    # In-cluster Kubernetes API
    server: https://kubernetes.default.svc
    # Dedicated namespace for NGINX
    namespace: nginx

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
