apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # Name of the Apache child application
  name: apache-child
  namespace: argocd
spec:
  # ArgoCD project
  project: devops-project

  source:
    # Git repository containing application manifests
    repoURL: https://github.com/MrSharma151/argocd-demos.git
    # Git branch to track
    targetRevision: main
    # Path of Apache manifests inside the repo
    path: cli_approach/apache

  destination:
    # In-cluster Kubernetes API (BEST PRACTICE)
    server: https://kubernetes.default.svc
    # Dedicated namespace for Apache app
    namespace: apache

  syncPolicy:
    automated:
      # Remove resources deleted from Git
      prune: true
      # Revert manual changes automatically
      selfHeal: true
