apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # Name of the Online Shop child application
  name: online-shop-child
  namespace: argocd
spec:
  project: devops-project

  source:
    # Git repository containing declarative manifests
    repoURL: https://github.com/MrSharma151/argocd-demos.git
    targetRevision: main
    # Path of Online Shop application
    path: declarative_approach/online-shop

  destination:
    # In-cluster Kubernetes API
    server: https://kubernetes.default.svc
    # Dedicated namespace for Online Shop
    namespace: online-shop

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
